// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDoH90KiU58WrSfF6L-_hP23BlIz97GhQ',
    appId: '1:289803300653:ios:fd5f23e164d7ade5a66da4',
    messagingSenderId: '289803300653',
    projectId: 'diana-d94cb',
    storageBucket: 'diana-d94cb.firebasestorage.app',
    iosBundleId: 'com.example.diana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtieuFGP_5G50N_Mc1STXtVLBYT6ogH-8',
    appId: '1:289803300653:web:24424f112032f1c1a66da4',
    messagingSenderId: '289803300653',
    projectId: 'diana-d94cb',
    authDomain: 'diana-d94cb.firebaseapp.com',
    storageBucket: 'diana-d94cb.firebasestorage.app',
    measurementId: 'G-GNYQHPE0K3',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtieuFGP_5G50N_Mc1STXtVLBYT6ogH-8',
    appId: '1:289803300653:web:8e214cc4a4d048d3a66da4',
    messagingSenderId: '289803300653',
    projectId: 'diana-d94cb',
    authDomain: 'diana-d94cb.firebaseapp.com',
    storageBucket: 'diana-d94cb.firebasestorage.app',
    measurementId: 'G-YDCZ7W7XL1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDoH90KiU58WrSfF6L-_hP23BlIz97GhQ',
    appId: '1:289803300653:ios:fd5f23e164d7ade5a66da4',
    messagingSenderId: '289803300653',
    projectId: 'diana-d94cb',
    storageBucket: 'diana-d94cb.firebasestorage.app',
    iosBundleId: 'com.example.diana',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxBlPmiDlM-yTQ6J-bWZJQk6Q3HcBjjrw',
    appId: '1:289803300653:android:f8e8545ec9ed7843a66da4',
    messagingSenderId: '289803300653',
    projectId: 'diana-d94cb',
    storageBucket: 'diana-d94cb.firebasestorage.app',
  );

}