// ignore_for_file: unused_import

import 'package:diana/animations/splash_screen.dart';
import 'package:diana/auth/auth_gate.dart';
import 'package:diana/auth/login.dart';
import 'package:diana/pages/chat_screen.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // 💡 Required for Firebase
import 'firebase_options.dart'; // 💡 Generated by `flutterfire configure`
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const ChatApp());
}

class ChatApp extends StatelessWidget {
  const ChatApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color(0xFF1C1C1E),
      ),
      home: const SplashScreen(), // 🔥 Start with Splash
    );
  }
}